### PR TITLE
Remove spam from security

### PR DESCRIPTION
**Pull request by penn5**

### CODE REVIEW

**Comment by raphielscape** [comment]
We actually can just return it silently rather than announcing it, also I propose that we should disable evaluation module by default and putting it under debug modules that shouldn't enabled by default

**Comment by zakaryan2004** [comment]
Is it tested?

**Comment by zakaryan2004** [comment]
> We actually can just return it silently rather than announcing it, also I propose that we should disable evaluation module by default and putting it under debug modules that shouldn't enabled by default

+1 on this. I don't see a proper use for the exec module actually. At least they aren't enough to compensate for the risks.

**Comment by AvinashReddy3108** [comment]
> We actually can just return it silently rather than announcing it, also I propose that we should disable evaluation module by default and putting it under debug modules that shouldn't enabled by default

Until we do that, https://github.com/RaphielGang/Telegram-Paperplane/pull/224 could be merged. Coz it's really annoying to see those messages popping up when anyone uses an inline bot.

**Comment by RealAkito** [comment]
#224 have addressed the problem, I see no reason for this PR to be open.

Closing.

**Pull request closed without merging**
