### PR TITLE
Rewrote 'Kicking away' ban phrase

### PR DESCRIPTION
**Pull request by Oxigen96**
Fixed from PR into master to staging

### CODE REVIEW

**Comment by zakaryan2004** [comment]
This change is completely unnecessary. Please put more effort into Pull Requests.

**Comment by baalajimaestro** [comment]
doing for hacktoberfest plis help

**Comment by zakaryan2004** [comment]
exactly

**Comment by zakaryan2004** [comment]
Like, I can merge it now and it'd benefit my hacktoberfest as well, but no

also he has made only one PR in October

**Pull request closed without merging**
