### PR TITLE
scrapers: google: catch NoResultsOrTrafficError exception

### PR DESCRIPTION
**Pull request by Stricted**
* log error to BOTLOG channel if available

Change-Id: I308551c692a40ca2f21d28c7cabfa66551b7db18

### CODE REVIEW

**Review by raphielscape — APPROVED** [review]
LGTM

**Comment by Stricted** [comment]
missed the import :/

**Comment by zakaryan2004** [comment]
It may be better not to touch the old BOTLOG behavior by removing the success log. If something like this is to be done, it should be done treewide. I am planning to do a logger overhaul soon.

**Comment by zakaryan2004** [comment]
The last line (* remove useless logging while at it) should be removed from the commit message.

Otherwise, approved.

**Review by zakaryan2004 — APPROVED** [review]

**Pull request merged**
