### PR TITLE
promote: only grant permissions that we have ourselves

### PR DESCRIPTION
**Pull request by Stricted**
Change-Id: Id961491ae4dfd04a1acdf42b8d6823e5e2b18488

### CODE REVIEW

**Comment by zakaryan2004** [comment]
Please rebase the pull request on staging.

**Comment by zakaryan2004** [comment]
Sorry for messing your master branch up a bit, but hopefully you can fix it later. 

So there are still people using Paperplane... Maybe it's time to resurrect it again, who knows?

I also pushed a small change. If you don't have any other improvements on this PR, I'll merge

**Comment by Stricted** [comment]
no worries, made the fork only for this pr anyway

i dont really mess with python so i wasnt sure what the correct way to deal with this is

for now i have no further changes but i guess i will send more PR's once i come across other things

**Comment by zakaryan2004** [comment]
Thanks for contributing to and using the (kinda dead) Paperplane.

**Pull request merged**
