### PR TITLE
Fixed some DeepSource issues

### PR DESCRIPTION
**Pull request by eliastheis**
I found your repo in DeepSource and found a couple of issues to fix. This is my first pull request in an opensource project and I hope it is accepted.
best regards
Elias

### CODE REVIEW

**Comment by zakaryan2004** [comment]
There is clearly something wrong with this. Fix your pull request. Have separate pull requests for each change.

**Comment by eliastheis** [comment]
@zakaryan2004 Do you know why there are 82 commits? If I look [here](https://github.com/eliastheis/PaperplaneMinimal/commits/master), you see that there are only 3 commits from me.
I am very confused.

**Comment by zakaryan2004** [comment]
> @zakaryan2004 Do you know why there are 82 commits? If I look [here](https://github.com/eliastheis/PaperplaneMinimal/commits/master), you see that there are only 3 commits from me.
> I am very confused.

Pull requests don't work on the "commits by me" basis. That repo is based on a fork of Paperplane, which has many more commits, and you have done your changes on that fork, not the upstream ("original") Paperplane. Thus, when you do a pull request to the upstream Paperplane repo, GitHub adds all the new commits to the pull request. You should clone this repo and do your changes on it. Knowing some git and how GitHub works will help you.

**Comment by zakaryan2004** [comment]
Also, we only accept pull requests to the staging branch.

**Comment by eliastheis** [comment]
So should I clone the staging branch and change my stuff there? And then do a pull request from there?
Sorry for the extra work. I'm relatively new here and try to contribute to opensource projects.

**Comment by zakaryan2004** [comment]
> So should I clone the staging branch and change my stuff there? And then do a pull request from there?
> Sorry for the extra work. I'm relatively new here and try to contribute to opensource projects.

Yes.

**Comment by raphielscape** [comment]
Fixed in 230284e6d7ea6bac6976a5642a6c36883aa9c12b

**Pull request closed without merging**
