### PR TITLE
updated my username

### PR DESCRIPTION
**Pull request by xencodes**
this commit updates my username in the README file

### CODE REVIEW

**Comment by raphielscape** [comment]
Rebase to the Staging branch

**Comment by zakaryan2004** [comment]
Do it properly

**Comment by skittles9823** [comment]
Wew double credits for me

**Comment by xencodes** [comment]
> > Wew double credits for me
> 
> Don't worry, this critical bug will be fixed

lol - i am sorry

**Comment by AvinashReddy3108** [comment]
Add my name too while you're at it :eyes:

**Comment by zakaryan2004** [comment]
I am updating it based on the Contributions page, everyone will be added properly, don't worry

**Pull request closed without merging**
